home/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from django.shortcuts import render
from django.conf.urls import handler404
from django.conf.urls import handler500

def error404(request):
	return render(request, '404.html', status=404)
	
def error500(request):
	return render(request, '500.html', status=500)
	
handler404 = error404
handler500 = error500

urlpatterns = patterns('',
	url(r'^$', include('main.urls', namespace="main")),
	url(r'^news/', include('news.urls', namespace="news")),
	url(r'^organizators/', include('organizators.urls', namespace="organizators")),
	url(r'^contact/', include('contact.urls', namespace="contact")),
	url(r'^partners/', include('partners.urls', namespace="partners")),
	url(r'^presentation/', include('presentation.urls', namespace="presentation")),
	url(r'^spikers/', include('spikers.urls', namespace="spikers")),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^pages/', include('django.contrib.flatpages.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

main/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
 url(r'^$', views.index, name='index'),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}" />
	<meta charset="utf-8" />
    <title>{% block title %}Конференции{% endblock %}</title>
	
	<link href="{% static 'favicon.ico' %}" rel="shortcut icon" type="image/vnd.microsoft.icon">
	{% block head_data %}{% endblock %}
</head>
<body>
<header>
	<div id="header">
		<div class="width-page header">
			<a href="/" class="logo">Конференции</a>
			<div class="user-panel">
				{% if user.is_authenticated %}
				Добро пожаловать, {{ user.username }} <a href="/admin" target="_blank" >Админ панель</a> | <a href="/admin/logout/">Выйти</a>
				{% else %}
				<a href="/admin">Войти</a>
				{% endif %}
			</div>
		</div>
		<div class="sidebar">
			<ul class="width-page ul">
				<li><a href="/" class="{% block active_main %}{% endblock %}">Главная</a></li>
				<li><a href="{% url 'spikers:index' %}" class="{% block active_spikers %}{% endblock %}">Спикеры</a></li>
				<li><a href="{% url 'presentation:index' %}" class="{% block active_presentation %}{% endblock %}">Выступления</a></li>
				<li><a href="{% url 'organizators:index' %}" class="{% block active_organ %}{% endblock %}">Организаторы</a></li>
				<li><a href="{% url 'partners:index' %}" class="{% block active_partners %}{% endblock %}">Партнеры</a></li>
				<li><a href="{% url 'contact:index' %}" class="{% block active_contact %}{% endblock %}">Контакты</a></li>
				<li><a href="{% url 'news:index' %}" class="{% block active_news %}{% endblock %}">Новости</a></li>
			</ul>
		</div>
	</div>
</header>
<article>
    <div id="article" class="width-page">
        {% block content %}{% endblock %}
    </div>
</article>
<footer>
	<div id="footer" class="width-page">
		<div>
		<a href="../../../../pages/test/">FlatPage_TEST</a>
			2015, Design and development belongs to <a href="https://vk.com/verd_mny">Helena</a>, 141-321 Study Group, University of Engineering MAMI
		</div>
	</div>
</footer>
</body>
</html>