home/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from django.shortcuts import render
from django.conf.urls import handler404
from django.conf.urls import handler500

def error404(request):
	return render(request, '404.html', status=404)
	
def error500(request):
	return render(request, '500.html', status=500)
	
handler404 = error404
handler500 = error500

urlpatterns = patterns('',
	url(r'^$', include('main.urls', namespace="main")),
	url(r'^news/', include('news.urls', namespace="news")),
	url(r'^organizators/', include('organizators.urls', namespace="organizators")),
	url(r'^contact/', include('contact.urls', namespace="contact")),
	url(r'^partners/', include('partners.urls', namespace="partners")),
	url(r'^presentation/', include('presentation.urls', namespace="presentation")),
	url(r'^spikers/', include('spikers.urls', namespace="spikers")),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^pages/', include('django.contrib.flatpages.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

partners/urls.py
from django.conf.urls import patterns, url
from partners import views
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
    url(r'^add/', views.add, name='add'),
	url(r'^(?P<partner_id>[0-9]+)/delete/$', views.delete, name='delete'),
	url(r'^(?P<partner_id>[0-9]+)/edit/$', views.edit, name='edit'), 
)

partners/models.py
from django.db import models

# Create your models here.
class Partners(models.Model):
	logotype = models.ImageField(upload_to='partners/logotype')
	partner_name =  models.CharField(max_length=255)
	description = models.TextField()
  	def __str__(self):
		return self.partner_name
		

partners/forms.py
#! coding: utf-8
from django import forms
from .models import Partners

class PartnersForm(forms.ModelForm):
   class Meta:
		model = Partners
		fields = ['logotype','partner_name','description']
		labels = {
            'logotype': ('Логотип'),
			'partner_name': ('Наименование'),
			'description': ('Описание'),
        }

class PartnersForm_Edit(forms.ModelForm):
   class Meta:
		model = Partners
		fields = ['partner_name','description']
		labels = {
			'partner_name': ('Наименование'),
			'description': ('Описание'),
        }

partners/views.py
#! coding: utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

#Кэширование на уровне представлений http://djbook.ru/rel1.5/topics/cache.html#the-per-view-cache
from django.views.decorators.cache import cache_page

# функция генерирующая 404 страницу
from django.http import Http404

# Create your views here.
from .forms import PartnersForm
from .forms import PartnersForm_Edit
from .models import Partners

def index(request):
	partners_list = Partners.objects.all()
	context = {'partners_list': partners_list}
	return render(request, 'partners/index.html', context)

@cache_page(60 * 15)
def add(request):
	if request.method == 'POST':
		form = PartnersForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/partners/')
	else:
		form = PartnersForm()
	
	return render(request, 'partners/add.html', {'form': form})

def delete(request, partner_id):
	try:
		Partners.objects.get(id=partner_id).delete()
	except Partners.DoesNotExist:
		return HttpResponseRedirect('/partners/')
	return HttpResponseRedirect('/partners/')

@cache_page(60 * 3)
def edit(request, partner_id):
	if request.method == 'POST':
		form = PartnersForm_Edit(request.POST)
		if form.is_valid():
			data_dict = {'partner_name': request.POST["partner_name"],'description': request.POST["description"]}
			Partners.objects.filter(id=partner_id).update(**data_dict)
			return HttpResponseRedirect('/partners/')
	else:
		try:
			article = Partners.objects.get(id=partner_id)
			form = PartnersForm_Edit(instance=article)
		except Partners.DoesNotExist:
			#если такого поста нет, то генерируем 404
			#raise Http404
			#включенный DEBUG=True блокирует отображение
			#стандартных шаблонов, по этому использую прямое включение
			return render(request, '404.html')
	return render(request, 'partners/edit.html', {'form': form,'partner_id':partner_id})

templates/partners/add.html
{% extends "base.html" %}
{% load static %}
{% block title %}Добавлнеие партнера{% endblock %}

{% block head_data %}
		<link rel="stylesheet" href="{% static 'partners/css/partners.css' %}" />
{% endblock %}

{% block content %}
	<div class="main_text">Добавление партнера</div>
	<form id="form-partner" enctype="multipart/form-data" action="{% url 'partners:add' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Отправить"/>
	</form>
{% endblock %}

templates/partners/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Изменение партнера{% endblock %}

{% block head_data %}
		<link rel="stylesheet" href="{% static 'partners/css/partners.css' %}" />
{% endblock %}

{% block content %}
	<div class="main_text">Изменение партнера</div>
	<form id="form-partner" enctype="multipart/form-data" action="{% url 'partners:index' %}{{partner_id}}/edit/" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Отправить"/>
	</form>
{% endblock %}

templates/partners/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Партнеры{% endblock %}

{% block head_data %}
		<link rel="stylesheet" href="{% static 'partners/css/partners.css' %}" />
{% endblock %}

{% block active_partners %}active{% endblock %}

{% block content %}
	<div class="main_text">Наши партнеры{% if user.is_authenticated %}<span><a href="{% url 'partners:add' %}">Добавить партнера</a></span>{% endif %}</div>
	{% if partners_list  %}
	<ul class="ul list">
	{% for partners in partners_list %}
		<li>
			<div class="block_top">
				<div id="partner-del"><a onclick='if(confirm("Удалить партнера?")){return true;} else {return false;}' href="{% url 'partners:index' %}{{ partners.id }}/delete"><div></div></a></div>
				<div id="partner-edit"><a href="{% url 'partners:index' %}{{ partners.id }}/edit"><div></div></a></div>
				<div style="background-image: url('{{ partners.logotype.url }}');" class="image"></div>
				<div class="title" title="{{ partners.partner_name}}">{{ partners.partner_name|truncatechars:26 }}</div>
			</div>
			<div class="block_bottom">
				<div class="description">{{ partners.description }}</div>
			</div>
		</li>
		{% cycle '' '' '<div style="overflow: auto;width:100%;"></div>' as rowflow %}
		{{ rowflow }}
	{% endfor %}
	</ul>
	{% else %}
		<div class="main_notification">Партнеры отсутствуют.</div>
	{% endif %}
{% endblock %}